### ISSUE TITLE
[BUG] Tool Tip should be available on the right panel , incase of hovering on icon( usability issue)

### ISSUE THREAD

**Issue by NoureenKhawaja** [sign/translate#109]
### Current Behavior

when i hover on icons , just above the "send feedback "text,  then icon should have tool tip so that user should not the purpose of this icon

### Expected Behavior

Tool Tip should display[](url)

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

### Additional context

![image](https://github.com/sign/translate/assets/146812315/b2a32b25-f74f-43b6-add9-9d14caefa3c1)
![Capture](https://github.com/sign/translate/assets/146812315/f38c7ad4-e56e-45fa-84a7-15837fc3a302)

**Comment by AmitMY** [comment]
Thanks for this issue!

Fixed in https://github.com/sign/translate/commit/889fd59bc7a1d09bae62cb035d514d98c76b9bb3
<img width="150" alt="image" src="https://github.com/sign/translate/assets/5757359/0f883ddb-d559-40a5-89ce-423ebc30c88a">

The online app should update soon.

**Comment by NoureenKhawaja** [comment]
Thanks now user can see the Tool Tip
