### ISSUE TITLE
Text section should have Auto spell  functionality  

### ISSUE THREAD

**Issue by NoureenKhawaja** [sign/translate#111]
### Current Behavior

On text section 
-if user enter  "Hapy" word  then

System check "auto spell" similar like word then ask user to correct word to get the correct Pose

### Expected Behavior

![image](https://github.com/sign/translate/assets/146812315/f6eb9786-dd6f-4546-95c3-282a76575d68)
"Hapy" word should highlighted  with Red  and detect the auto spell functionality similar like MS Word

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
This is described in the paper (https://arxiv.org/pdf/2310.05064.pdf) as something that should be done in the "text normalization" step.
Nevertheless, I am with you on this and have made spellchecking available again https://github.com/sign/translate/commit/dcfa0f512c4e07d4a870c7e64b343084c028444f
