### ISSUE TITLE
[BUG] WHY CAN'T YOU TRANSLATE SIGN TO TEXT????!!!!!!!

### ISSUE THREAD

**Issue by iownasignlanguageapp** [sign/translate#117]
### Current Behavior

CAN'T SIGN TO TEXT

### Expected Behavior

ABLE TO SIGN TO TEXT

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
Please be respectful when opening issues in open source projects.

The status of each pipeline is https://github.com/sign/translate/wiki/Spoken-to-Signed and https://github.com/sign/translate/wiki/Signed-to-Spoken 
At the moment, most of the time investment is going toward the Spoken-to-Signed pipeline. Once more stable, we will turn to the Signed-to-Spoken pipeline
