### ISSUE TITLE
Need more Resources

### ISSUE THREAD

**Issue by bipinkrish** [sign/translate#123]
## Description

I want to test this model with Python, when tried to convert with `tensorflowjs_converter`  i encountered this [issue](https://github.com/tensorflow/tfjs/issues/8088) 

Can I get one of these
- The code for training and the training data
- The model file that you trained with python (before converted to Tensorflow.js format)

**Comment by AmitMY** [comment]
Seems like you are trying to convert the face model.
Training code in python https://colab.research.google.com/drive/1io4XM11EpYi3HNadABhDZYBjPdvZrFcd?usp=sharing

Full explanation of what is done here: https://youtu.be/bwCNLiksILU?t=126

Note, that only this face features were trained on (no asymetric features)
![image](https://github.com/sign/translate/assets/5757359/1251ef58-a346-4339-b7d0-68b04a563fb5)

**Comment by AmitMY** [comment]
Detection is here https://github.com/sign-language-processing/detection-train
Animation is still actively being worked on, here https://github.com/sign-language-processing/pose-to-video/tree/main/pose_to_video/unconditional/mixamo

**Comment by bipinkrish** [comment]
Thank you
