### ISSUE TITLE
Human Model is not working 

### ISSUE THREAD

**Issue by imsamimalik** [sign/translate#124]
### Current Behavior

![image](https://github.com/sign/translate/assets/42075879/e3e66d7d-003a-4f94-aa0e-40a5c1418d9c)

When I select the human option from the dropdown, it just keeps on loading.

**Comment by AmitMY** [comment]
This is what I am seeing:
![image](https://github.com/sign/translate/assets/5757359/73836217-478e-49ba-ac13-71e2a6b6dc3f)

What browser are you using?
Are there any errors in the console? (https://documentation.concretecms.org/tutorials/how-open-browser-console-view-errors)

**Comment by imsamimalik** [comment]
My bad. There was some issue with Chrome Linux. It is working fine on Windows.

**Comment by imsamimalik** [comment]
For The 3D model, have you looked into implementing something like Ready Player Me [API](https://readyplayer.me/)?  Since you are already using Mediapipe, it would be fairly easy to implement it using MediaPipe Holistic landmarks. 

I am currently working on making a 3D character animated from a source video using MediaPipe. Let me know if I can be of any help.

**Comment by AmitMY** [comment]
I haven't looked at their API before, but I also don't see anything implying they have an API to rig using MediaPipe? Could you point me in the right direction? I'd love to include it of course if possible.

**Comment by imsamimalik** [comment]
I got intrigued when I found this [demo](https://mediapipe-facelandmark-demo.vercel.app/). He is extracting FaceLandmarks using MediaPipe and then using those landmarks he is Ready Player Me GLB model in the threejs. 

I thought that if  FaceLandmaks are possible then PoseLandmarks can be animated as well. 

I also had a chance to look at [Kalidokit](https://github.com/yeemachine/kalidokit/). He is using VRM 3D models instead of Ready Player Me but the approach is the same (extracting full body landmarks using media pipe and then animating characters.)

For the 3D animation then you wouldn't need to send the whole file. At the Python backend, you can just extract the landmarks from the video and send those landmarks array as API response.

**Comment by AmitMY** [comment]
For the face demo, they are not using landmarks. Instead, they are using blendshapes.

Kalidokit is more promising to work directly from landmarks.

**Comment by imsamimalik** [comment]
Sorry, forgot about the blendshapes. But, when the new Holistic API gets released(which should be in a few weeks, according to [this](https://github.com/google/mediapipe/issues/5054#issuecomment-1881493404)), Kalidokit + MediaPipe Holistic + Ready Player Me seems like the meta for me.

**Comment by AmitMY** [comment]
Closing since we already have an issue about Kalidokit #121
