### ISSUE TITLE
[Feature] SignWriting Textual Description

### ISSUE THREAD

**Issue by AmitMY** [sign/translate#130]
### Problem

Understanding how to perform SignWriting exactly can be a little difficult to non-linguists.

### Description

In addition to illustration (#114), we can include textual description of SignWriting.
In a zero-shot setting, we can describe where every symbol is placed, and it's name, and ask ChatGPT to describe it

Given the signs:
```
𝠃𝤘𝤣񁲡𝣳𝣩񈩧𝤉𝣻 
𝠃𝤘𝤧񃊫𝣻𝤕񃊢𝣴𝣼񆇡𝤎𝤂񋛕𝤆𝣦 񏌁𝣢𝤂
```

I would like to send them to ChatGPT as an image + as a rough textual description (hand 5 fingers, alternating arrows, and positions), and get "wave an open hand back and forth" or something similar

**Comment by AmitMY** [comment]
Repository to get this done https://github.com/sign-language-processing/signwriting-description

**Comment by AmitMY** [comment]
Implemented in https://github.com/sign/translate/commit/794c64c3aa93ec54d3c8e5a72832c81a1b335edd - does not perform well

**Comment by ashar02** [comment]
Hi, I saw the commit https://github.com/sign/translate/commit/794c64c3aa93ec54d3c8e5a72832c81a1b335edd it iss uing the api /api/signwriting-description. But in cloud function not route is there for signwriting-description? Is there something that you will commit later on?

**Comment by AmitMY** [comment]
We are using this implementation - https://github.com/sign-language-processing/signwriting-description
Just deployed using python on a GCP instance, and routed in the project definition: 
https://github.com/sign/translate/blob/91f180674fce12f7d951209f8ce1c995e742990f/firebase.json#L95-L96

**Comment by ashar02** [comment]
On sign.mt are you using GPT or naive for signwriting description?
