### ISSUE TITLE
[BUG] <npm install failed>

### ISSUE THREAD

**Issue by saravanan6137** [sign/translate#134]
### Current Behavior

After cloning the project when I run npm install command and its failing to install the dependencies.

### Expected Behavior

Should install the dependencies to run the project.

### Example flow

```
paste your flow here
```

### Environment

- Device: MAC
- OS: M1
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

### Additional context

<img width="1034" alt="Screenshot 2024-02-07 at 5 58 00 PM" src="https://github.com/sign/translate/assets/68968235/ac2cede1-b87b-468f-b53c-5625fe511d13">

**Comment by AmitMY** [comment]
Please include the log, in text form (inside a quote/code bracket), as well as the content of `/Users/....-debug-0.log`

**Comment by saravanan6137** [comment]
0 verbose cli /Users/saravanankannan/.nvm/versions/node/v18.19.0/bin/node /Users/saravanankannan/.nvm/versions/node/v18.19.0/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.2.3
2 info using node@v18.19.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/saravanankannan/.nvm/versions/node/v18.19.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/saravanankannan/.npm/_cacache/tmp/git-clonebg3wze/.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/Users/saravanankannan/.npmrc Completed in 3ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:/Users/saravanankannan/.nvm/versions/node/v18.19.0/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 13ms
17 timing npm:load:configload Completed in 13ms
18 timing config:load:flatten Completed in 3ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install
22 verbose argv "install" "--force" "--cache" "/Users/saravanankannan/.npm" "--prefer-offline" "false" "--prefer-online" "false" "--offline" "false" "--no-progress" "--no-save" "--no-audit" "--include" "dev" "--include" "peer" "--include" "optional" "--no-package-lock-only" "--no-dry-run"
23 timing npm:load:setTitle Completed in 8ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/saravanankannan/.npm/_logs/2024-02-09T02_22_01_053Z-
26 verbose logfile /Users/saravanankannan/.npm/_logs/2024-02-09T02_22_01_053Z-debug-0.log
27 timing npm:load:logFile Completed in 12ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 warn using --force Recommended protections disabled.
31 timing npm:load Completed in 47ms
32 timing arborist:ctor Completed in 0ms
33 silly logfile start cleaning logs, removing 1 files
34 timing idealTree:init Completed in 84ms
35 timing idealTree:userRequests Completed in 0ms
36 silly idealTree buildDeps
37 timing idealTree:#root Completed in 0ms
38 timing idealTree:buildDeps Completed in 1ms
39 timing idealTree:fixDepFlags Completed in 0ms
40 timing idealTree Completed in 85ms
41 silly logfile done cleaning log files
42 timing reify:loadTrees Completed in 87ms
43 timing reify:diffTrees Completed in 2ms
44 silly reify moves {}
45 timing reify:retireShallow Completed in 1ms
46 timing reify:createSparse Completed in 17ms
47 timing reify:loadBundles Completed in 0ms
48 timing reifyNode:node_modules/spdx-exceptions Completed in 448ms
49 timing reifyNode:node_modules/eastasianwidth Completed in 458ms
50 timing reifyNode:node_modules/boolbase Completed in 458ms
51 timing reifyNode:node_modules/wrappy Completed in 462ms
52 timing reifyNode:node_modules/wide-align Completed in 466ms
53 timing reifyNode:node_modules/wrap-ansi Completed in 466ms
54 timing reifyNode:node_modules/validate-npm-package-license Completed in 467ms
55 timing reifyNode:node_modules/universalify Completed in 468ms
56 timing reifyNode:node_modules/strip-final-newline Completed in 469ms
57 timing reifyNode:node_modules/strip-json-comments Completed in 469ms
58 timing reifyNode:node_modules/slice-ansi Completed in 469ms
59 timing reifyNode:node_modules/spdx-license-ids Completed in 469ms
60 timing reifyNode:node_modules/simple-swizzle Completed in 470ms
61 timing reifyNode:node_modules/shebang-command Completed in 470ms
62 timing reifyNode:node_modules/process-nextick-args Completed in 471ms
63 timing reifyNode:node_modules/pretty Completed in 471ms
64 timing reifyNode:node_modules/path-parse Completed in 471ms
65 timing reifyNode:node_modules/path-is-absolute Completed in 472ms
66 timing reifyNode:node_modules/parse-json Completed in 473ms
67 timing reifyNode:node_modules/object-assign Completed in 473ms
68 timing reifyNode:node_modules/normalize-path Completed in 473ms
69 timing reifyNode:node_modules/number-is-nan Completed in 473ms
70 timing reifyNode:node_modules/mkdirp-classic Completed in 473ms
71 timing reifyNode:node_modules/once Completed in 473ms
72 timing reifyNode:node_modules/ms Completed in 473ms
73 timing reifyNode:node_modules/min-indent Completed in 474ms
74 timing reifyNode:node_modules/merge-stream Completed in 474ms
75 timing reifyNode:node_modules/log-update/node_modules/slice-ansi Completed in 474ms
76 timing reifyNode:node_modules/log-update/node_modules/wrap-ansi Completed in 474ms
77 timing reifyNode:node_modules/listr2/node_modules/slice-ansi Completed in 474ms
78 timing reifyNode:node_modules/lighthouse-logger/node_modules/ms Completed in 475ms
79 timing reifyNode:node_modules/is-whitespace Completed in 474ms
80 timing reifyNode:node_modules/is-number Completed in 474ms
81 timing reifyNode:node_modules/is-plain-obj Completed in 474ms
82 timing reifyNode:node_modules/is-extendable Completed in 475ms
83 timing reifyNode:node_modules/ini Completed in 475ms
84 timing reifyNode:node_modules/inflight Completed in 475ms
85 timing reifyNode:node_modules/has-flag Completed in 475ms
86 timing reifyNode:node_modules/has-unicode Completed in 475ms
87 timing reifyNode:node_modules/gauge/node_modules/string-width Completed in 475ms
88 timing reifyNode:node_modules/gauge/node_modules/strip-ansi Completed in 476ms
89 timing reifyNode:node_modules/gauge/node_modules/ansi-regex Completed in 476ms
90 timing reifyNode:node_modules/error-ex Completed in 476ms
91 timing reifyNode:node_modules/extend-shallow Completed in 476ms
92 timing reifyNode:node_modules/end-of-stream Completed in 476ms
93 timing reifyNode:node_modules/gauge/node_modules/is-fullwidth-code-point Completed in 476ms
94 timing reifyNode:node_modules/escape-string-regexp Completed in 477ms
95 timing reifyNode:node_modules/decamelize-keys Completed in 477ms
96 timing reifyNode:node_modules/decamelize Completed in 477ms
97 timing reifyNode:node_modules/condense-newlines Completed in 476ms
98 timing reifyNode:node_modules/condense-newlines/node_modules/kind-of Completed in 476ms
99 timing reifyNode:node_modules/color-name Completed in 476ms
100 timing reifyNode:node_modules/color-string Completed in 476ms
101 timing reifyNode:node_modules/code-point-at Completed in 476ms
102 timing reifyNode:node_modules/chownr Completed in 476ms
103 timing reifyNode:node_modules/buffer-crc32 Completed in 477ms
104 timing reifyNode:node_modules/brace-expansion Completed in 477ms
105 timing reifyNode:node_modules/decamelize-keys/node_modules/map-obj Completed in 478ms
106 timing reifyNode:node_modules/at-least-node Completed in 477ms
107 timing reifyNode:node_modules/arrify Completed in 477ms
108 timing reifyNode:node_modules/aproba Completed in 477ms
109 timing reifyNode:node_modules/abbrev Completed in 477ms
110 timing reifyNode:node_modules/@types/yauzl Completed in 477ms
111 timing reifyNode:node_modules/@types/normalize-package-data Completed in 477ms
112 timing reifyNode:node_modules/wrap-ansi/node_modules/strip-ansi Completed in 482ms
113 timing reifyNode:node_modules/wrap-ansi/node_modules/is-fullwidth-code-point Completed in 482ms
114 timing reifyNode:node_modules/@types/minimist Completed in 478ms
115 timing reifyNode:node_modules/@babel/highlight/node_modules/ansi-styles Completed in 478ms
116 timing reifyNode:node_modules/wrap-ansi/node_modules/ansi-regex Completed in 482ms
117 timing reifyNode:node_modules/wide-align/node_modules/is-fullwidth-code-point Completed in 481ms
118 timing reifyNode:node_modules/wide-align/node_modules/strip-ansi Completed in 481ms
119 timing reifyNode:node_modules/wrap-ansi/node_modules/string-width Completed in 482ms
120 timing reifyNode:node_modules/wide-align/node_modules/string-width Completed in 481ms
121 timing reifyNode:node_modules/wide-align/node_modules/ansi-regex Completed in 482ms
122 timing reifyNode:node_modules/webidl-conversions Completed in 482ms
123 timing reifyNode:node_modules/to-regex-range Completed in 482ms
124 timing reifyNode:node_modules/tunnel-agent Completed in 482ms
125 timing reifyNode:node_modules/trim-newlines Completed in 483ms
126 timing reifyNode:node_modules/strip-indent Completed in 483ms
127 timing reifyNode:node_modules/slash Completed in 483ms
128 timing reifyNode:node_modules/string-width Completed in 483ms
129 timing reifyNode:node_modules/strip-ansi Completed in 483ms
130 timing reifyNode:node_modules/shebang-regex Completed in 483ms
131 timing reifyNode:node_modules/signal-exit Completed in 483ms
132 timing reifyNode:node_modules/set-blocking Completed in 483ms
133 timing reifyNode:node_modules/restore-cursor Completed in 483ms
134 timing reifyNode:node_modules/read-pkg Completed in 483ms
135 timing reifyNode:node_modules/quick-lru Completed in 484ms
136 timing reifyNode:node_modules/redent Completed in 484ms
137 timing reifyNode:node_modules/read-pkg-up Completed in 484ms
138 timing reifyNode:node_modules/path-exists Completed in 483ms
139 timing reifyNode:node_modules/pkg-dir Completed in 483ms
140 timing reifyNode:node_modules/pend Completed in 483ms
141 timing reifyNode:node_modules/p-try Completed in 483ms
142 timing reifyNode:node_modules/p-locate Completed in 483ms
143 timing reifyNode:node_modules/p-map Completed in 483ms
144 timing reifyNode:node_modules/p-limit Completed in 483ms
145 timing reifyNode:node_modules/onetime Completed in 483ms
146 timing reifyNode:node_modules/path-key Completed in 483ms
147 timing reifyNode:node_modules/parse5-htmlparser2-tree-adapter Completed in 483ms
148 timing reifyNode:node_modules/mimic-response Completed in 484ms
149 timing reifyNode:node_modules/npm-run-path Completed in 484ms
150 timing reifyNode:node_modules/map-obj Completed in 484ms
151 timing reifyNode:node_modules/log-update/node_modules/ansi-regex Completed in 484ms
152 timing reifyNode:node_modules/log-update/node_modules/strip-ansi Completed in 485ms
153 timing reifyNode:node_modules/log-update/node_modules/string-width Completed in 485ms
154 timing reifyNode:node_modules/lru-cache Completed in 485ms
155 timing reifyNode:node_modules/log-update/node_modules/is-fullwidth-code-point Completed in 485ms
156 timing reifyNode:node_modules/mimic-fn Completed in 486ms
157 timing reifyNode:node_modules/log-update Completed in 486ms
158 timing reifyNode:node_modules/locate-path Completed in 486ms
159 timing reifyNode:node_modules/listr2/node_modules/string-width Completed in 486ms
160 timing reifyNode:node_modules/lodash.uniqwith Completed in 486ms
161 timing reifyNode:node_modules/listr2/node_modules/strip-ansi Completed in 486ms
162 timing reifyNode:node_modules/listr2/node_modules/ansi-regex Completed in 487ms
163 timing reifyNode:node_modules/listr2/node_modules/cli-truncate Completed in 487ms
164 timing reifyNode:node_modules/minimist-options Completed in 487ms
165 timing reifyNode:node_modules/is-stream Completed in 486ms
166 timing reifyNode:node_modules/listr2/node_modules/is-fullwidth-code-point Completed in 487ms
167 timing reifyNode:node_modules/json-parse-even-better-errors Completed in 486ms
168 timing reifyNode:node_modules/is-wsl Completed in 487ms
169 timing reifyNode:node_modules/is-fullwidth-code-point Completed in 487ms
170 timing reifyNode:node_modules/ieee754 Completed in 487ms
171 timing reifyNode:node_modules/inherits Completed in 487ms
172 timing reifyNode:node_modules/indent-string Completed in 487ms
173 timing reifyNode:node_modules/fs-constants Completed in 487ms
174 timing reifyNode:node_modules/find-up Completed in 488ms
175 timing reifyNode:node_modules/fill-range Completed in 488ms
176 timing reifyNode:node_modules/editorconfig/node_modules/lru-cache Completed in 488ms
177 timing reifyNode:node_modules/decompress-response Completed in 488ms
178 timing reifyNode:node_modules/config-chain Completed in 487ms
179 timing reifyNode:node_modules/console-control-strings Completed in 488ms
180 timing reifyNode:node_modules/cli-cursor Completed in 489ms
181 timing reifyNode:node_modules/color Completed in 489ms
182 timing reifyNode:node_modules/clean-stack Completed in 489ms
183 timing reifyNode:node_modules/camelcase-keys Completed in 490ms
184 timing reifyNode:node_modules/chalk/node_modules/supports-color Completed in 490ms
185 timing reifyNode:node_modules/core-util-is Completed in 490ms
186 timing reifyNode:node_modules/camelcase Completed in 490ms
187 timing reifyNode:node_modules/chalk/node_modules/has-flag Completed in 490ms
188 timing reifyNode:node_modules/cli-truncate Completed in 504ms
189 timing reifyNode:node_modules/astral-regex Completed in 505ms
190 timing reifyNode:node_modules/aggregate-error Completed in 506ms
191 timing reifyNode:node_modules/@babel/highlight Completed in 506ms
192 timing reifyNode:node_modules/@babel/highlight/node_modules/supports-color Completed in 506ms
193 timing reifyNode:node_modules/ansi-regex Completed in 507ms
194 timing reifyNode:node_modules/yallist Completed in 511ms
195 timing reifyNode:node_modules/@babel/code-frame Completed in 508ms
196 timing reifyNode:node_modules/util-deprecate Completed in 511ms
197 timing reifyNode:node_modules/wrap-ansi/node_modules/ansi-styles Completed in 513ms
198 timing reifyNode:node_modules/string_decoder Completed in 512ms
199 timing reifyNode:node_modules/string-argv Completed in 512ms
200 timing reifyNode:node_modules/spdx-correct Completed in 513ms
201 timing reifyNode:node_modules/proto-list Completed in 516ms
202 timing reifyNode:node_modules/minimatch Completed in 515ms
203 timing reifyNode:node_modules/log-update/node_modules/ansi-styles Completed in 516ms
204 timing reifyNode:node_modules/listr2/node_modules/ansi-styles Completed in 516ms
205 timing reifyNode:node_modules/lighthouse-logger Completed in 516ms
206 timing reifyNode:node_modules/lilconfig Completed in 516ms
207 timing reifyNode:node_modules/js-tokens Completed in 515ms
208 timing reifyNode:node_modules/kind-of Completed in 515ms
209 timing reifyNode:node_modules/lines-and-columns Completed in 517ms
210 timing reifyNode:node_modules/is-buffer Completed in 516ms
211 timing reifyNode:node_modules/is-docker Completed in 517ms
212 timing reifyNode:node_modules/hard-rejection Completed in 518ms
213 timing reifyNode:node_modules/extract-zip Completed in 518ms
214 timing reifyNode:node_modules/fs.realpath Completed in 518ms
215 timing reifyNode:node_modules/expand-template Completed in 519ms
216 timing reifyNode:node_modules/editorconfig/node_modules/yallist Completed in 519ms
217 timing reifyNode:node_modules/chalk/node_modules/ansi-styles Completed in 518ms
218 timing reifyNode:node_modules/balanced-match Completed in 519ms
219 timing reifyNode:node_modules/base64-js Completed in 519ms
220 timing reifyNode:node_modules/ansi-styles Completed in 520ms
221 timing reifyNode:node_modules/ansi-escapes Completed in 520ms
222 timing reifyNode:node_modules/which Completed in 523ms
223 timing reifyNode:node_modules/supports-color Completed in 525ms
224 timing reifyNode:node_modules/simple-concat Completed in 526ms
225 timing reifyNode:node_modules/pump Completed in 527ms
226 timing reifyNode:node_modules/pseudomap Completed in 530ms
227 timing reifyNode:node_modules/npmlog Completed in 535ms
228 timing reifyNode:node_modules/mkdirp Completed in 535ms
229 timing reifyNode:node_modules/mime-types Completed in 536ms
230 timing reifyNode:node_modules/meow Completed in 536ms
231 timing reifyNode:node_modules/napi-build-utils Completed in 536ms
232 timing reifyNode:node_modules/micromatch Completed in 536ms
233 timing reifyNode:node_modules/lodash.isequal Completed in 536ms
234 timing reifyNode:node_modules/get-stream Completed in 536ms
235 timing reifyNode:node_modules/has Completed in 537ms
236 timing reifyNode:node_modules/extract-zip/node_modules/get-stream Completed in 537ms
237 timing reifyNode:node_modules/domelementtype Completed in 537ms
238 timing reifyNode:node_modules/deep-extend Completed in 538ms
239 timing reifyNode:node_modules/are-we-there-yet/node_modules/safe-buffer Completed in 538ms
240 timing reifyNode:node_modules/are-we-there-yet/node_modules/string_decoder Completed in 538ms
241 timing reifyNode:node_modules/@babel/highlight/node_modules/color-name Completed in 538ms
242 timing reifyNode:node_modules/yauzl Completed in 543ms
243 timing reifyNode:node_modules/simple-swizzle/node_modules/is-arrayish Completed in 542ms
244 timing reifyNode:node_modules/spdx-expression-parse Completed in 545ms
245 timing reifyNode:node_modules/sigmund Completed in 545ms
246 timing reifyNode:node_modules/rimraf Completed in 545ms
247 timing reifyNode:node_modules/safe-buffer Completed in 546ms
248 timing reifyNode:node_modules/jsonfile Completed in 545ms
249 timing reifyNode:node_modules/isarray Completed in 546ms
250 timing reifyNode:node_modules/is-arrayish Completed in 547ms
251 timing reifyNode:node_modules/hosted-git-info Completed in 547ms
252 timing reifyNode:node_modules/colorette Completed in 547ms
253 timing reifyNode:node_modules/@ionic/utils-array Completed in 548ms
254 timing reifyNode:node_modules/read-pkg/node_modules/hosted-git-info Completed in 553ms
255 timing reifyNode:node_modules/progress Completed in 554ms
256 timing reifyNode:node_modules/puppeteer-core/node_modules/debug Completed in 554ms
257 timing reifyNode:node_modules/prebuild-install/node_modules/detect-libc Completed in 554ms
258 timing reifyNode:node_modules/husky Completed in 554ms
259 timing reifyNode:node_modules/delegates Completed in 555ms
260 timing reifyNode:node_modules/concat-map Completed in 554ms
261 timing reifyNode:node_modules/color-convert Completed in 554ms
262 timing reifyNode:node_modules/debug Completed in 555ms
263 timing reifyNode:node_modules/@ionic/utils-fs Completed in 555ms
264 timing reifyNode:node_modules/@babel/highlight/node_modules/color-convert Completed in 555ms
265 timing reifyNode:node_modules/@babel/helper-validator-identifier Completed in 556ms
266 timing reifyNode:node_modules/nopt Completed in 558ms
267 timing reifyNode:node_modules/isexe Completed in 557ms
268 timing reifyNode:node_modules/graceful-fs Completed in 558ms
269 timing reifyNode:node_modules/detect-libc Completed in 559ms
270 timing reifyNode:node_modules/dom-serializer Completed in 559ms
271 timing reifyNode:node_modules/are-we-there-yet Completed in 558ms
272 timing reifyNode:node_modules/@babel/highlight/node_modules/chalk Completed in 558ms
273 timing reifyNode:node_modules/read-pkg/node_modules/semver Completed in 561ms
274 timing reifyNode:node_modules/tar-stream Completed in 561ms
275 timing reifyNode:node_modules/sax Completed in 561ms
276 timing reifyNode:node_modules/proxy-from-env Completed in 562ms
277 timing reifyNode:node_modules/glob Completed in 562ms
278 timing reifyNode:node_modules/editorconfig/node_modules/semver Completed in 562ms
279 timing reifyNode:node_modules/chalk Completed in 562ms
280 timing reifyNode:node_modules/wrap-ansi/node_modules/emoji-regex Completed in 567ms
281 timing reifyNode:node_modules/wide-align/node_modules/emoji-regex Completed in 566ms
282 timing reifyNode:node_modules/tslib Completed in 566ms
283 timing reifyNode:node_modules/supports-preserve-symlinks-flag Completed in 566ms
284 timing reifyNode:node_modules/simple-get Completed in 566ms
285 timing reifyNode:node_modules/log-update/node_modules/emoji-regex Completed in 565ms
286 timing reifyNode:node_modules/listr2/node_modules/emoji-regex Completed in 566ms
287 timing reifyNode:node_modules/cross-spawn Completed in 565ms
288 timing reifyNode:node_modules/editorconfig/node_modules/commander Completed in 566ms
289 timing reifyNode:node_modules/whatwg-url Completed in 569ms
290 timing reifyNode:node_modules/fd-slicer Completed in 568ms
291 timing reifyNode:node_modules/marky Completed in 570ms
292 timing reifyNode:node_modules/is-core-module Completed in 569ms
293 timing reifyNode:node_modules/buffer Completed in 569ms
294 timing reifyNode:node_modules/through Completed in 574ms
295 timing reifyNode:node_modules/read-pkg/node_modules/normalize-package-data Completed in 574ms
296 timing reifyNode:node_modules/rfdc Completed in 574ms
297 timing reifyNode:node_modules/nth-check Completed in 579ms
298 timing reifyNode:node_modules/normalize-package-data Completed in 579ms
299 timing reifyNode:node_modules/github-from-package Completed in 578ms
300 timing reifyNode:node_modules/function-bind Completed in 579ms
301 timing reifyNode:node_modules/domhandler Completed in 580ms
302 timing reifyNode:node_modules/cheerio-select Completed in 579ms
303 timing reifyNode:node_modules/find-process/node_modules/commander Completed in 581ms
304 timing reifyNode:node_modules/rc Completed in 585ms
305 timing reifyNode:node_modules/https-proxy-agent Completed in 584ms
306 timing reifyNode:node_modules/braces Completed in 584ms
307 timing reifyNode:node_modules/prebuild-install Completed in 586ms
308 timing reifyNode:node_modules/css-what Completed in 586ms
309 timing reifyNode:node_modules/bl Completed in 587ms
310 timing reifyNode:node_modules/agent-base Completed in 587ms
311 timing reifyNode:node_modules/picomatch Completed in 589ms
312 timing reifyNode:node_modules/execa Completed in 589ms
313 timing reifyNode:node_modules/read-pkg/node_modules/type-fest Completed in 591ms
314 timing reifyNode:node_modules/unbzip2-stream Completed in 592ms
315 timing reifyNode:node_modules/node-abi Completed in 591ms
316 timing reifyNode:node_modules/node-fetch Completed in 591ms
317 timing reifyNode:node_modules/mime-db Completed in 593ms
318 timing reifyNode:node_modules/find-process Completed in 592ms
319 timing reifyNode:node_modules/editorconfig Completed in 594ms
320 timing reifyNode:node_modules/human-signals Completed in 596ms
321 timing reifyNode:node_modules/tr46 Completed in 600ms
322 timing reifyNode:node_modules/lighthouse-logger/node_modules/debug Completed in 599ms
323 timing reifyNode:node_modules/commander Completed in 602ms
324 timing reifyNode:node_modules/yargs-parser Completed in 607ms
325 timing reifyNode:node_modules/gauge Completed in 604ms
326 timing reifyNode:node_modules/read-pkg-up/node_modules/type-fest Completed in 607ms
327 timing reifyNode:node_modules/emoji-regex Completed in 607ms
328 timing reifyNode:node_modules/minimist Completed in 609ms
329 timing reifyNode:node_modules/entities Completed in 608ms
330 timing reifyNode:node_modules/elementtree Completed in 645ms
331 timing reifyNode:node_modules/htmlparser2 Completed in 648ms
332 timing reifyNode:node_modules/ws Completed in 651ms
333 timing reifyNode:node_modules/domutils Completed in 650ms
334 timing reifyNode:node_modules/lint-staged Completed in 653ms
335 timing reifyNode:node_modules/are-we-there-yet/node_modules/readable-stream Completed in 655ms
336 timing reifyNode:node_modules/readable-stream Completed in 660ms
337 timing reifyNode:node_modules/meow/node_modules/type-fest Completed in 661ms
338 timing reifyNode:node_modules/chrome-launcher Completed in 669ms
339 timing reifyNode:node_modules/cordova-res Completed in 669ms
340 timing reifyNode:node_modules/object-inspect Completed in 674ms
341 timing reifyNode:node_modules/tar-fs Completed in 676ms
342 timing reifyNode:node_modules/node-addon-api Completed in 679ms
343 timing reifyNode:node_modules/css-select Completed in 677ms
344 timing reifyNode:node_modules/pwa-asset-generator Completed in 681ms
345 timing reifyNode:node_modules/type-fest Completed in 689ms
346 timing reifyNode:node_modules/semver Completed in 694ms
347 timing reifyNode:node_modules/fs-extra Completed in 702ms
348 timing reifyNode:node_modules/cheerio Completed in 707ms
349 timing reifyNode:node_modules/parse5 Completed in 711ms
350 timing reifyNode:node_modules/sharp Completed in 716ms
351 timing reifyNode:node_modules/listr2 Completed in 725ms
352 timing reifyNode:node_modules/yaml Completed in 728ms
353 timing reifyNode:node_modules/js-beautify Completed in 741ms
354 timing reifyNode:node_modules/@types/node Completed in 755ms
355 timing reifyNode:node_modules/resolve Completed in 766ms
356 timing reifyNode:node_modules/devtools-protocol Completed in 780ms
357 timing reifyNode:node_modules/puppeteer-core Completed in 982ms
358 timing reifyNode:node_modules/prettier Completed in 1173ms
359 timing reifyNode:node_modules/rxjs Completed in 1566ms
360 timing reifyNode:node_modules/@material-icons/svg Completed in 11118ms
361 timing reify:unpack Completed in 11122ms
362 timing reify:unretire Completed in 1ms
363 timing build:queue Completed in 4ms
364 timing build:link:node_modules/cordova-res Completed in 3ms
365 timing build:link:node_modules/editorconfig/node_modules/semver Completed in 2ms
366 timing build:link:node_modules/editorconfig Completed in 3ms
367 timing build:link:node_modules/find-process Completed in 3ms
368 timing build:link:node_modules/extract-zip Completed in 3ms
369 timing build:link:node_modules/detect-libc Completed in 3ms
370 timing build:link:node_modules/read-pkg/node_modules/semver Completed in 2ms
371 timing build:link:node_modules/is-docker Completed in 3ms
372 timing build:link:node_modules/husky Completed in 3ms
373 timing build:link:node_modules/mkdirp Completed in 3ms
374 timing build:link:node_modules/nopt Completed in 3ms
375 timing build:link:node_modules/lint-staged Completed in 3ms
376 timing build:link:node_modules/js-beautify Completed in 3ms
377 timing build:link:node_modules/prettier Completed in 3ms
378 timing build:link:node_modules/prebuild-install Completed in 3ms
379 timing build:link:node_modules/pwa-asset-generator Completed in 3ms
380 timing build:link:node_modules/rc Completed in 3ms
381 timing build:link:node_modules/rimraf Completed in 3ms
382 timing build:link:node_modules/which Completed in 2ms
383 timing build:link:node_modules/resolve Completed in 3ms
384 timing build:link:node_modules/semver Completed in 3ms
385 timing build:link Completed in 4ms
386 info run sharp@0.29.3 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
387 info run sharp@0.29.3 install { code: 0, signal: null }
388 timing build:run:install:node_modules/sharp Completed in 1463ms
389 timing build:run:install Completed in 1463ms
390 timing build:deps Completed in 1471ms
391 timing build Completed in 1471ms
392 timing reify:build Completed in 1471ms
393 timing reify:trash Completed in 0ms
394 timing reify Completed in 12739ms
395 timing command:install Completed in 12876ms
396 verbose stack Error: command failed
396 verbose stack     at ChildProcess.<anonymous> (/Users/saravanankannan/.nvm/versions/node/v18.19.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
396 verbose stack     at ChildProcess.emit (node:events:517:28)
396 verbose stack     at maybeClose (node:internal/child_process:1098:16)
396 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
397 verbose pkgid @sign/configuration@0.0.1
398 verbose cwd /Users/saravanankannan/.npm/_cacache/tmp/git-clonebg3wze
399 verbose Darwin 22.6.0
400 verbose node v18.19.0
401 verbose npm  v10.2.3
402 error code 1
403 error path /Users/saravanankannan/.npm/_cacache/tmp/git-clonebg3wze
404 error command failed
405 error command sh -c husky install
406 verbose exit 1
407 timing npm Completed in 13097ms
408 verbose code 1
409 error A complete log of this run can be found in: /Users/saravanankannan/.npm/_logs/2024-02-09T02_22_01_053Z-debug-0.log

**Comment by AmitMY** [comment]
You are using node 18.19.0
The LTS is node 20, can you please try with node 20?
https://nodejs.org/en
