### ISSUE TITLE
Text-to-Text Translation

### ISSUE THREAD

**Issue by bipinkrish** [sign/translate#136]
## Description

1. [Text-to-Text](https://github.com/sign/translate/tree/master/functions/src/text-to-text), is that the same thing as you explained here at [research.sign.mt](https://research.sign.mt/) as `Notation-to-Text` ?

2. I see that API path is not working as mentioned in [README.md](https://github.com/sign/translate/blob/master/functions/src/text-to-text/README.md) - `https://sign.mt/api/spoken-to-signed?from=en&to=ase&text=test`. but you are using `https://pub.cl.uzh.ch/demo/signwriting/spoken2sign` in the project

3. When I checked it out, with the following payload

```
{
    'country_code': 'ase',
    'language_code': 'en',
    'text': 'hi',
    'translation_type': 'sent',
}
```

this is what I received as response 

```
{
    "country_code": "ase",
    "direction": "spoken2sign",
    "language_code": "en",
    "n_best": 3,
    "text": "hi",
    "translation_type": "sent",
    "translations": [
        "M518x518S14c01483x461S2ff00482x483",
        "M518x518S14c20481x453S27106503x484",
        "M518x518S14c01483x461S2ff00482x483S22510473x457",
    ],
}
```

can you tell me how can I visualize `translations`? is that `SignWriting` notations?

**Comment by AmitMY** [comment]
Yes, this text-to-text is spoken-language-text-to-sign-language-text (or notation).

This endpoint we currently use belongs to https://github.com/J22Melody/signwriting-translation/
The translations here can be visualized using `@sutton-signwriting/sgnw-components` in JavaScript or `signwriting` in python.

**Comment by bipinkrish** [comment]
Thank you, [found it](https://github.com/sign-language-processing/signwriting)

**Comment by ashar02** [comment]
Hi, implementation of this api https://pub.cl.uzh.ch/demo/signwriting/spoken2sig is open source or closed source?

**Comment by bipinkrish** [comment]
> J22Melody/signwriting-translation

@ashar02, It has to be used with [signbank+](https://github.com/sign-language-processing/signbank-plus)

**Comment by ashar02** [comment]
Thanks @AmitMY @bipinkrish
