### ISSUE TITLE
[BUG] App crashing on npm start

### ISSUE THREAD

**Issue by anash3420** [sign/translate#137]
### Current Behavior

<img width="1512" alt="image" src="https://github.com/sign/translate/assets/64568938/93493e92-6d84-4db9-872a-bb050c8cc821">

### Expected Behavior

Should compile and run on the localhost

### Steps To Reproduce

I tried the same steps given in readme 

git clone 
npm i 
npm start

### Example flow

```
paste your flow here
```

### Environment

- Device: Macbook M1 pro
- OS: (MacOS Sonoma)
- Browser: Chrome
- Version: latest
-  Node - 20.11.0

### Additional context

I'm new to angular hence it can be something that I may have missed while setting up the project. If so please guide me to it

**Comment by AmitMY** [comment]
I just want to make sure, all you did was:
```bash
git clone
npm install
npm run start
```

I am running on the same OS, with the same node version, and it works fine.

Maybe paste your entire build log (inside coding brackets here on github) to see what the issue is.
