### ISSUE TITLE
[Bug] Signed-to-Spoken translation doesn't work, stuck "Loading Pose Estimation"

### ISSUE THREAD

**Issue by gayathrib9865** [sign/translate#141]
### Problem

The Sign language to Text Conversion is not  working properly.I tried many times but the web stays "Loading Pose Estimation"

### Description

Give us permission to access that part of web

### Alternatives

Enable the Picture uploading option or scanning process of sign language to text conversion process make possible

**Comment by AmitMY** [comment]
If you are stuck on `Loading Pose Estimation`, please provide a screen recording / inform us what browser you are using.

In any case, the signed-to-spoken translation direction is work-in-progress, see [here](https://github.com/sign/translate/wiki/Signed-to-Spoken) for full implementation progress. It does not currently work on the web.
