### ISSUE TITLE
[BUG] Failed to start - `Can't resolve './node_modules/leaflet/dist/leaflet.css'`

### ISSUE THREAD

**Issue by AaryanNagaria** [sign/translate#144]
### Current Behavior

My goal is to run your app on my Mac through Xcode;  below is what I have tried so far:

1. I have cloned the app at /Users/aaryannagaria/Documents/translate/translate

2. I then installed Node.js onto my Mac as mentioned in your README

3. I ran “npm install” at /Users/aaryannagaria/Documents/translate/translate and it was good

4. I then ran “npm start” which is giving me error Can't resolve './node_modules/leaflet/dist/leaflet.css' in '/Users/aaryannagaria/Documents/translate/translate'

Thank you for reading and I would greatly appreciate it if you could help me run this project on my Mac. 

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
1. What node version are you using `node --version`
2. What is the output of `ls node_modules/leaflet/` (is the module installed?)
3. If it is installed, what is the output of `ls node_modules/leaflet/dist`

**Comment by AaryanNagaria** [comment]
Node Version: v20.11.1

Output of ls node_modules/leaflet/: 
CHANGELOG.md	README.md	package.json
LICENSE		dist		src

Output of ls node_modules/leaflet/dist:
images			leaflet-src.js		leaflet.js
leaflet-src.esm.js	leaflet-src.js.map	leaflet.js.map
leaflet-src.esm.js.map	leaflet.css

**Comment by AmitMY** [comment]
hmm... your error is:
> Can't resolve './node_modules/leaflet/dist/leaflet.css' in '/Users/aaryannagaria/Documents/translate/translate'

To me that means that if you run:
```
cd /Users/aaryannagaria/Documents/translate/translate
cat ./node_modules/leaflet/dist/leaflet.css
```
it should say the file does not exist, but from the output you sent me, the file does exist. So are you still getting this error?

If so, do you mind recording your screen, and running the following commands?

```bash
git clone https://github.com/sign/translate.git
cd translate
npm install
npm start
```

**Comment by AaryanNagaria** [comment]
https://github.com/sign/translate/assets/87981765/a6cfa034-035b-4dd1-915b-51ef19d6b2aa

This is my output, and everything is seeming to run fine now, but when I try to run npm test, it won't et me type anything.

**Comment by AmitMY** [comment]
Happy it runs fine now. (for future referece, the video is too compressed, I can't read anything, but I can see that it works)

`npm test` should run tests, not let you type. what do you mean by that?

**Comment by AaryanNagaria** [comment]
After I run npm start, it doesn’t give me a place to type npm test.
![Screenshot 2024-03-05 at 2 14 32 PM](https://github.com/sign/translate/assets/87981765/f71ff1f9-0f99-429f-88c1-21f006c8cf57)

**Comment by AmitMY** [comment]
I see. yes, `npm start` starts a process that does not end. you can open `http://localhost:4200` to see the site.

If you want to run test, you need to do that in another process. Open another terminal window, and run `npm test`

**Comment by AaryanNagaria** [comment]
I did that and this came up

Last login: Tue Mar  5 19:15:55 on ttys003
aaryannagaria@Aaryans-MBP ~ % npm test

> @sign/translate@0.0.3 test
> ng test --code-coverage

Error: This command is not available when running the Angular CLI outside a workspace.
aaryannagaria@Aaryans-MBP ~ %

**Comment by AmitMY** [comment]
You have to run it in the directory of the project, not in `~`

**Comment by AaryanNagaria** [comment]
I tried it and it worker. After I did that, it opened a tab on my google chrome, what should I do next?

**Comment by AmitMY** [comment]
It depends what you want to do.
If you want to test - https://angular.io/guide/testing
If you want to run - https://angular.io/start

**Comment by AaryanNagaria** [comment]
What should I do if I want to run your app.
