### ISSUE TITLE
[Q] I need to know the place of the model to see how data is going in and out to it , if you give me the place of it in files..

### ISSUE THREAD

**Issue by Nooraldenberkdar** [sign/translate#153]
### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
what model? what data? what direction?
closing. Please fill in an issue body.
