### ISSUE TITLE
Question about core of the project

### ISSUE THREAD

**Issue by Nooraldenberkdar** [sign/translate#154]
### Problem

This project is translating the Text into sign language 
1. are you using a model for this process?
2. if yes, where is the model I want to see it?
I am not a web developer so I don't know very well the structure of the project and how it works specifically

**Comment by AmitMY** [comment]
Information about the translation can be find in the wiki:
https://github.com/sign/translate/wiki/Spoken-to-Signed

Currently, this path is taken:
![annotely_image](https://github.com/sign/translate/assets/5757359/9ce527a1-85c4-47d3-8246-049d0855af39)

You can click any of the nodes to see where it is implemented (repository/model), and you are specifically looking for the "Glosses" link here.
