### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by Tortoise17** [sign/translate#155]
Dear Respected Fellows, I would like to ask that is there any training dataset available for the research and development. ? and any training source code? Specially for python or so.?

Best wishes. 

## Steps to Reproduce the Problem

1.
2.
3.

## Environment

- Platform: (e.g. Windows 10, macOS Big Sur, Ubuntu 20.04, iOS, Android)
- Browser: (e.g. Google Chrome 88, Mozilla Firefox 83, Safari 14)
- Any additional relevant information: (e.g. screen resolution, hardware specifications)

**Comment by AmitMY** [comment]
This repository is the application for inference.
To see what we are using, see our wiki https://github.com/sign/translate/wiki/Spoken-to-Signed
The graph includes links for various repositories that include training of various models at each step.

**Comment by Tortoise17** [comment]
@AmitMY Thank you. This inference is with some other language. Is there opensource inference which is python base?

**Comment by AmitMY** [comment]
@Tortoise17 Please look at the relevant repositories' README. They have "usage", usually with command line commands. That is pure python, and you can import it if you want.
If you have any question about another repository, open an issue there.
