### ISSUE TITLE
Building Source for iOS Development and Vietnamese Language Support

### ISSUE THREAD

**Issue by nqkhanh2002** [sign/translate#158]
## Description

I am encountering difficulties building a source code project for iOS development. I used Android Studio and ran npm commands for iOS, but I faced numerous errors. Additionally, I want to enhance my pipeline, which follows the flow text -> glosses -> pose sequence, to include Vietnamese language support. Although Vietnamese language detection is implemented using Google's cld3, the recognition part is missing. I need guidelines for adding Vietnamese language support, including any necessary data or modifications to the existing pipeline.

## Expected Behavior

1. The source code should build successfully for iOS without errors.
2. The pipeline should support Vietnamese language recognition.

## Actual Behavior

1. The build process fails with multiple errors.
2. Vietnamese language recognition is not implemented in the pipeline.

## Steps to Reproduce the Problem

1. Open Android Studio, Run the npm commands for iOS, Observe the errors that occur.
2. Review the pipeline steps from text -> glosses -> pose sequence for Vietnamese language support.

## Environment

1. Platform: Windows 10
2. Browser: Google Chrome 123
3. Additional Information: Building for iOS using Android Studio, npm commands, pipeline enhancements for Vietnamese language recognition

- Platform: (e.g. Windows 10, macOS Big Sur, Ubuntu 20.04, iOS, Android)
- Browser: (e.g. Google Chrome 88, Mozilla Firefox 83, Safari 14)
- Any additional relevant information: (e.g. screen resolution, hardware specifications)

**Comment by AmitMY** [comment]
There are two separate issues here.
Please create two separate issues.
