### ISSUE TITLE
Alphabet problem.

### ISSUE THREAD

**Issue by mips404** [sign/translate#166]
### Current Behavior

there's no problem when you type only the word "alphabet", but when you type "I learned the alphabet" it's just signing random stuff nonstop.

[Screen recording 2024-08-26 10.22.06 PM.webm](https://github.com/user-attachments/assets/22c72dd3-8412-47e1-8aef-e15dc02be7b9)

**Comment by AmitMY** [comment]
Fixed in https://github.com/sign-language-processing/spoken-to-signed-translation/commit/1dc84349621461d22c330b89b60c07d517e9b95d
