### ISSUE TITLE
[BUG] Can't translate the sign language using webcam

### ISSUE THREAD

**Issue by Moadbenyousef** [sign/translate#170]
### Current Behavior

when I'm trying to translate the sign language using my webcam it doesn't show any text translated .

### Expected Behavior

to detect the sign language i make and translate it to text

### Example flow

```
paste your flow here
```

### Environment

- Device: (laptop)
- OS: (Windows)
- Browser: (brave)
- Version: (v.1.70.123)

### Additional context

I'm working on that project for the deaf and mute school in Libya . for volunteer preposes .
If you can help me with this problem i would be so thankful . 
You can reach me using my email : moadbenyousef0@gmail.com
or my teammate:
mohimen.abuabdallah@gmail.com

**Comment by AmitMY** [comment]
The signed-to-spoken pipeline is not operational at the moment and requires additional research and integration.
You can check the status here: https://github.com/sign/translate/wiki/Signed-to-Spoken

**Comment by Moadbenyousef** [comment]
I think you misunderstood me, because what I mean is that when I open the camera and make gestures, no translation of the gesture I made appears on the other side, so I want to turn this thing on because it is very useful for schools for the deaf and dumb. @AmitMY

**Comment by AmitMY** [comment]
I understood. No, we currently do not support that translation direction.

Also, re `deaf and dumb`, please note https://disabilitycenter.colostate.edu/inclusive-language/
![image](https://github.com/user-attachments/assets/b7b0d260-f6a6-444f-8e64-070cc25686e7)

**Comment by Moadbenyousef** [comment]
I'm sorry I didn't mean that @AmitMY
