### ISSUE TITLE
[Feature] <AR language>

### ISSUE THREAD

**Issue by vm10ks** [sign/translate#173]
### Description

hello there thanks for reading my comment but by chance is there arabic  lang support? i was trying in arabic words but it didnt work

**Comment by AmitMY** [comment]
Correct, at the moment it seems like in our API, `ar` is not supported.
https://sign.mt/?spl=ar&sil=jos&text=%D8%B9%D9%84%D9%89

That should be fixed.
Also, the Arabic interface is not RTL https://sign.mt/?spl=ar&sil=jos&text=%D8%B9%D9%84%D9%89&lang=ar

**Comment by AmitMY** [comment]
Jordanian/Syrian sign language is now somewhat supported. It is of very low quality though.
https://sign.mt/?spl=ar&sil=jos&text=%D8%B9%D9%84%D9%89

**Comment by larawehbe** [comment]
how did you add it? and how can i add a new ArSL?
