### ISSUE TITLE
[Feature] <Display active word at the bottom for each gesture>

### ISSUE THREAD

**Issue by srishti-56** [sign/translate#175]
### Problem

The app currently translates entire sentences but its hard for me to learn which word corresponds to which gesture. Printing out the current word at the bottom of the gesture would help understand the sentence.

### Description

The active word corresponding to the gesture can be printed out as the gesture is performed. Printing out the current word at the bottom of the gesture would help understand the sentence.

**Comment by AmitMY** [comment]
Thanks for opening the issue.
While you are correct, we are currently translating "word-by-word", the goal of the app is not to be an educational tool necessarily, but to perform translation. In real translation, there is no one-to-one correspondence between words and signs, so eventually, this feature doesn't make sense for our app.

So to say: we are open to any wrapper around it to make it more educational. but it is not the goal of this specific app
