### ISSUE TITLE
Modify "Team" Section on About page

### ISSUE THREAD

**Issue by TimothyRbz** [sign/translate#183]
Various changes to the team section of the website to accurately reflect the most important and current information.

**Comment by TimothyRbz** [comment]
[ ] Adapt Text for Timothy: Background in LegalTech, politics, and business analysis, with a strong background in leading innovation in regulated industries. Holds a Master of Law with a focus on public law and innovation from the University of Bern.

**Comment by AmitMY** [comment]
Doing so creates a skewed layout (before, each person had 4 rows, now you have 6)
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/fd9e2cda-3dee-4b15-afd3-50adae18d40a">

I also think it is somewhat repetitive, and both sentences say slightly a different version of the same thing.

Can still execute if you prefer.

**Comment by TimothyRbz** [comment]
Agree with the layout issue:  Experienced in leading innovation in LegalTech, politics and regulated industries with a Master of Law from the University of Bern.

**Comment by AmitMY** [comment]
Nice. Also changed my title to Dr. 
<img width="893" alt="image" src="https://github.com/user-attachments/assets/67320bb2-6db8-4002-855b-c3374c9db2f1">
