### ISSUE TITLE
Modify "AI-Powerd Translation Section" on the About page

### ISSUE THREAD

**Issue by TimothyRbz** [sign/translate#184]
Customisation of the buttons: 

- [ ] Remove the ‘Competition’ button completely. 
- [ ] Update the ‘Try it out’ button by having same wording as the header (button redirecting to the demo page) for better user guidance.

**Comment by AmitMY** [comment]
Before:
![image](https://github.com/user-attachments/assets/97d5a8f4-da1d-4de5-a342-5a9104785b53)

After:
![image](https://github.com/user-attachments/assets/6000aeb0-6210-47e2-ac9d-f93a5dfae259)
