### ISSUE TITLE
[BUG] URL parameter style translation input is broken

### ISSUE THREAD

**Issue by J22Melody** [sign/translate#190]
### Current Behavior

For example:

https://sign.mt/?spl=de&sil=sgg&text=ich%20liebe%20dich%20sehr

now I try it, the input field is empty

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
Thanks for reporting! Fixed.
