### ISSUE TITLE
Inquiry on Data and Pipeline for Text-to-Sign Translation

### ISSUE THREAD

**Issue by Coolcoder009** [sign/translate#192]
### Problem

Hello Team,

First, thank you for your incredible work on this project—it’s inspiring to see advancements in text-to-sign language translation!

I was exploring your implementation, and I am curious about how the model generates pose sequences for a given sentence. Specifically, I’d like to understand the following:
Data Collection: How did you gather data for the various sign poses? Were these sequences sourced from an existing dataset, or were they custom-recorded for the project?
Pose Sequence Representation: Are the poses generated directly or interpolated between keyframes? If possible, could you share an overview (not the internal details, just the high-level approach) of how the translation pipeline is designed?

**Comment by AmitMY** [comment]
The specific pipeline you are after is described in https://github.com/sign-language-processing/spoken-to-signed-translation
We use existing sign language dictionaries, extract poses using https://github.com/sign-language-processing/pose and stitch them together

**Comment by Coolcoder009** [comment]
The pipeline is all clear, but i have to know in clear from where the video data have been taken. Please provide the source of the data you have used.
