### ISSUE TITLE
[BUG] <txt to sign>

### ISSUE THREAD

**Issue by Karim-Errahem** [sign/translate#195]
### Current Behavior

the sign to text transition always show "what is your name" only.

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
duplicate of #174
