### ISSUE TITLE
[BUG] <Text to Sign translation is not working translation as skeleton animation >

### ISSUE THREAD

**Issue by Muhammadkamranlive** [sign/translate#39]
### Current Behavior

**Loading sign is showing but the text to sign translation is not working**.
![image](https://user-images.githubusercontent.com/89290897/166871411-8c2889d9-8212-4b7c-95be-995c5ab9f516.png)

### Expected Behavior

**The text would be converted to animation skeleton animation.**
![image](https://user-images.githubusercontent.com/89290897/166871441-8b0c29aa-0dee-4ff6-b1f9-b2e0f1069667.png)

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
Thank you for reporting the issue.
I have managed to replicate it, and will work on fixing it in the coming days.

**Comment by AmitMY** [comment]
Please note, it works now without an update to the app required. Must have been an issue with the pose translation server
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/5757359/167283303-0bb1f142-d122-4d0f-99c3-06560d064f9f.png">
