### ISSUE TITLE
Add AppCheck support across all services

### ISSUE THREAD

**Issue by AmitMY** [sign/translate#51]
### Problem

Currently, all requests are unauthenticated. We ideally want to prevent unauthorized requests to our storage, database, and APIs

### Description

We should use Firebase AppCheck for storage and functions.

**Comment by IzzySoft** [comment]
Wouldn't Firebase rather make your app non-free (FOSS-wise, not price-wise)? Maybe [Supabase](https://supabase.com/) or [appwrite](https://github.com/appwrite/appwrite) would be a better choice. That said, is the app available anywhere already? I cannot find an APK here, nor do I see a link to [F-Droid](https://f-droid.org/) or any similar place.

**Comment by AmitMY** [comment]
AppCheck is now used for cloud functions like text normalization https://github.com/sign/translate/blob/master/src/app/modules/translate/translate.service.ts#L170

**Comment by AmitMY** [comment]
To complete this issue:
- [ ] Functions: Create an intercepter to add the headers for both python and node API endpoints, for everything under `sign.mt/api/`
- [ ] Storage: figure out how to add AppCheck to storage

**Comment by AmitMY** [comment]
For storage, manually adding `token=` OR the `X` headers did not register as verified. 
Should consider using https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/storage

**Comment by AmitMY** [comment]
AppCheck is now done in storage (using the abovementioned library).
We can not yet enforce AppCheck on the entire project's storage since other projects are using it as well.
