### ISSUE TITLE
Errors when installing dependencies

### ISSUE THREAD

**Issue by kexinsee2019** [sign/translate#71]
## Actual Behavior

I tried installing the dependencies using `npm i` but there were errors

![image](https://user-images.githubusercontent.com/88883095/218992037-ac98b209-0c5c-441c-9855-1856e18d9342.png)

my current npm version is 9.4.2 and my current node version is 19.6.0. I did try downgrading npm to 8.0.0 and node to 16.0.0 as stated but the same errors pop out. please assist!

## Environment
- Platform: Windows 10

**Comment by AmitMY** [comment]
One option would have been to use `bash` on windows.
I implemented a fix: https://github.com/sign/translate/commit/b35ec0d54aa0db2606e457cc0e8fd389c30d67dd
