### ISSUE TITLE
[BUG] I Installation dependency errors

### ISSUE THREAD

**Issue by arnaudnjita** [sign/translate#77]
### Current Behavior

Running `npm install --save` I get the following dependency errors as shown below

![image](https://user-images.githubusercontent.com/50627574/223176988-c7966c45-6013-460e-ab01-b315f3fd04e9.png)

### Expected Behavior

The installation is expected to go to completion installing all the necessary dependencies required for the project to run.

### Steps To Reproduce

Run `npm install --save` or `npm install --save --legacy-peer-deps`

### Example flow

```
paste your flow here
```

### Environment

- Device: (Laptop)
- OS: (Windows 11)
- Browser: (Firefox)
- Version: (110.0)

**Comment by AmitMY** [comment]
```
npm install --legacy-peer-deps
```
Is correct.
The error you are getting, as it says, is a timeout to the npm servers.
Just try again.
![image](https://user-images.githubusercontent.com/5757359/223199019-c8102422-a41b-45b3-b90f-17dcdcd07f49.png)

**Comment by arnaudnjita** [comment]
Alright thank you
