### ISSUE TITLE
[Feature] Spoken-to-signed Endpoint

### ISSUE THREAD

**Issue by AmitMY** [sign/translate#95]
### Problem

Currently, the endpoint is hosted on Bar-Ilan University servers, and is not easy to modify

### Description

We should make a python cloud function that calls:
https://github.com/ZurichNLP/spoken-to-signed-translation

Inputs:
- Text
- Spoken language
- Signed language

Process:
- **normalize** the text (https://github.com/ZurichNLP/spoken-to-signed-translation/issues/6) 
- run `text_to_gloss_to_pose` against database

Outputs:
- binary pose file as a response

**Comment by AmitMY** [comment]
Done in a closed source deployment, available at: https://us-central1-sign-mt.cloudfunctions.net/spoken_text_to_signed_pose

**Comment by bipinkrish** [comment]
> Done in a closed source deployment

is there a plan to make it open source

**Comment by MuhammadAasharibNawshad** [comment]
Is the code for this url available somewhere? https://us-central1-sign-mt.cloudfunctions.net/spoken_text_to_signed_pose.
I donot want to change the method and use it unchanged.

**Comment by AmitMY** [comment]
This repository is open source https://github.com/ZurichNLP/spoken-to-signed-translation
The endpoint is closed-source since it directly accesses a different pose dataset, but then all it does is call the library and nothing else.

**Comment by MuhammadAasharibNawshad** [comment]
So my understanding for https://us-central1-sign-mt.cloudfunctions.net/spoken_text_to_signed_pose is that it basically has different lexical for different languages. And whenever the API is called, it returns pose for that particular spoken to sign language lexical. Can you please tell whether my understanding regarding this Endpoint is correct or not?

**Comment by AmitMY** [comment]
There are many lexicons, for many signed languages. whenever the endpoint is hit, it takes signs from that specific lexicon, and stitches them.
This is the same as done in the open source implementation, just that it uses an SQL database instead of a CSV file
