### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ShakeelKhalid1913** [sign/translate#96]
No documentation? I want to understand the code and its been a month. and because of no documentation, I didn't understand anything.

**Comment by AmitMY** [comment]
Do you have any specific questions? I could add documentation, I just need to know what is not clear

**Comment by AmitMY** [comment]
Seems like what you care about specifically is the pose estimation and mixamo animation system (4).
I have made a video about it: https://youtu.be/TyJuU9_GOaw
As you can see from the video, the character **does not** follow the pose correctly.
You can try it yourself here: https://sign.mt/playground
(Hit "Turn on Camera" and activate "Animate pose")

Holistic is used to get the keypoints, and the animation with Mixamo is just a model I trained.

To move a mixamo model in the web, the process is as done here:
https://github.com/sign/translate/blob/master/src/app/components/animation/animation.component.ts#L58-L78

---

These days I am writing a paper that improves on the model in the video.
When I finish, and when it is stable, I hope to have a better model that actually animates correctly based on the pose

**Comment by ShakeelKhalid1913** [comment]
Great. I really appreciate your help. 

We were trying to animate the character, but it did not work correctly because of Animating Quaternion Rotation. 
Can you provide me with the model you used to animate the Mixamo in this repo? or any tutorial online by which I can do animation from pose estimation points.
I need a tutorial on sign animation of some English essential words like Hello, Good, and You with code explanation including Animating Quaternion Rotation in three js whether it could be a simple node js project or React (Also the main issue is I'm not angular guy which is big problem xD). 

We are students and this is our final year BS computer science project. We have researched many papers. we have checked HandTalk mobile application too. but they didn't even provide any explanation of how they did.
It would be great if you can help to share tutorial with us.

**Comment by AmitMY** [comment]
I won't be able to make a tutorial, the YouTube video is the best I can do for you.

Pose service: https://github.com/sign/translate/blob/master/src/app/modules/pose/pose.service.ts
Animation service: https://github.com/sign/translate/blob/master/src/app/modules/animation/animation.service.ts
Model is in `src/assets/models/pose-animation/model.json`

**Comment by AmitMY** [comment]
For other models to animate avatars from mediapipe: https://github.com/yeemachine/kalidokit

**Comment by ShakeelKhalid1913** [comment]
Great. Thank you for you help :)
